//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RGBSyncPlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RGBSyncPlus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string _ {
            get {
                return ResourceManager.GetString(".", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string __ {
            get {
                return ResourceManager.GetString("..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one-stop utlility for syncing your RGB perhipherals and components. Compatible with Corsair iCUE, Asus AURA, Razer Synapse, Logitech Gaming, EVGA Precision X1, and Cooler Master Masterplus..
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JackNet RGB Sync v1.8.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string AffirmativeCommand {
            get {
                return ResourceManager.GetString("AffirmativeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplyLabel {
            get {
                return ResourceManager.GetString("ApplyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available LEDs.
        /// </summary>
        public static string AvaliableLEDsLabel {
            get {
                return ResourceManager.GetString("AvaliableLEDsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Update.
        /// </summary>
        public static string CheckUpdateCommand {
            get {
                return ResourceManager.GetString("CheckUpdateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string ClientHeading {
            get {
                return ResourceManager.GetString("ClientHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string ClipboardCommand {
            get {
                return ResourceManager.GetString("ClipboardCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup delay:.
        /// </summary>
        public static string DelayLabel {
            get {
                return ResourceManager.GetString("DelayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines how long to wait, if at all, before the program starts..
        /// </summary>
        public static string DelayTooltip {
            get {
                return ResourceManager.GetString("DelayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string DelayUnit {
            get {
                return ResourceManager.GetString("DelayUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices:.
        /// </summary>
        public static string DevicesLabel {
            get {
                return ResourceManager.GetString("DevicesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord RPC:.
        /// </summary>
        public static string DiscordLabel {
            get {
                return ResourceManager.GetString("DiscordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Discord Rich Presence.
        /// </summary>
        public static string DiscordText {
            get {
                return ResourceManager.GetString("DiscordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays that you are using JackNet RGB Sync as well as the name of the active profile on your Discord profile..
        /// </summary>
        public static string DiscordTooltip {
            get {
                return ResourceManager.GetString("DiscordTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Client.
        /// </summary>
        public static string EnableClientLabel {
            get {
                return ResourceManager.GetString("EnableClientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Server.
        /// </summary>
        public static string EnableServerLabel {
            get {
                return ResourceManager.GetString("EnableServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVGA support written by emulamer.
        /// </summary>
        public static string EVGANotice {
            get {
                return ResourceManager.GetString("EVGANotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Devices.
        /// </summary>
        public static string ExcludeBtn {
            get {
                return ResourceManager.GetString("ExcludeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitItem {
            get {
                return ResourceManager.GetString("ExitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Groups.
        /// </summary>
        public static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature requires Premium. Would you like to go to the webpage where you can purchase Premium?.
        /// </summary>
        public static string FeatureNotAvailable {
            get {
                return ResourceManager.GetString("FeatureNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string GroupNameLabel {
            get {
                return ResourceManager.GetString("GroupNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Groups.
        /// </summary>
        public static string ImportButton {
            get {
                return ResourceManager.GetString("ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string InstalledLabel {
            get {
                return ResourceManager.GetString("InstalledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join my Discord server.
        /// </summary>
        public static string JoinDiscordButton {
            get {
                return ResourceManager.GetString("JoinDiscordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Opensource Licenses.
        /// </summary>
        public static string LicenseButton {
            get {
                return ResourceManager.GetString("LicenseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Plugins.
        /// </summary>
        public static string ManagePluginsBtn {
            get {
                return ResourceManager.GetString("ManagePluginsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control LED:.
        /// </summary>
        public static string MasterLEDLabel {
            get {
                return ResourceManager.GetString("MasterLEDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimization:.
        /// </summary>
        public static string MinimizationLabel {
            get {
                return ResourceManager.GetString("MinimizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Minimization.
        /// </summary>
        public static string MinimizationText {
            get {
                return ResourceManager.GetString("MinimizationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSI support written by Hex3l..
        /// </summary>
        public static string MSINotice {
            get {
                return ResourceManager.GetString("MSINotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NegativeCommand {
            get {
                return ResourceManager.GetString("NegativeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New LED Group.
        /// </summary>
        public static string NewGroupButton {
            get {
                return ResourceManager.GetString("NewGroupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No LED group selected ....
        /// </summary>
        public static string NoGroupSelected {
            get {
                return ResourceManager.GetString("NoGroupSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Installed.
        /// </summary>
        public static string NotInstalledLabel {
            get {
                return ResourceManager.GetString("NotInstalledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update found. You are currently using the latest version of the application..
        /// </summary>
        public static string NoUpdateText {
            get {
                return ResourceManager.GetString("NoUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Update Available.
        /// </summary>
        public static string NoUpdateTitle {
            get {
                return ResourceManager.GetString("NoUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKCommand {
            get {
                return ResourceManager.GetString("OKCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open UI.
        /// </summary>
        public static string OpenUIItem {
            get {
                return ResourceManager.GetString("OpenUIItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LED Groups.
        /// </summary>
        public static string Page1Header {
            get {
                return ResourceManager.GetString("Page1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Page2Header {
            get {
                return ResourceManager.GetString("Page2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Page3Header {
            get {
                return ResourceManager.GetString("Page3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Page4Header {
            get {
                return ResourceManager.GetString("Page4Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick File.
        /// </summary>
        public static string PickFileLabel {
            get {
                return ResourceManager.GetString("PickFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling Rate:.
        /// </summary>
        public static string PollingRateLabel {
            get {
                return ResourceManager.GetString("PollingRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines how fast the data is updated. Low value reduce CPU usage but might cause stuttering..
        /// </summary>
        public static string PollingRateTooltip {
            get {
                return ResourceManager.GetString("PollingRateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates per Second.
        /// </summary>
        public static string PollingRateUnit {
            get {
                return ResourceManager.GetString("PollingRateUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Premium.
        /// </summary>
        public static string PremiumCTAButton {
            get {
                return ResourceManager.GetString("PremiumCTAButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature not Available.
        /// </summary>
        public static string PremiumFeatureTitle {
            get {
                return ResourceManager.GetString("PremiumFeatureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium:.
        /// </summary>
        public static string PremiumLabel {
            get {
                return ResourceManager.GetString("PremiumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Name:.
        /// </summary>
        public static string ProfileNameLabel {
            get {
                return ResourceManager.GetString("ProfileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove LED Group?.
        /// </summary>
        public static string RemoveHeader {
            get {
                return ResourceManager.GetString("RemoveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete the group.
        /// </summary>
        public static string RemovePrompt {
            get {
                return ResourceManager.GetString("RemovePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart App.
        /// </summary>
        public static string RestartAppItem {
            get {
                return ResourceManager.GetString("RestartAppItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JackNet RGB Sync is powered by RGB.NET by Darth Affe.
        /// </summary>
        public static string RGBNetNotice {
            get {
                return ResourceManager.GetString("RGBNetNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as Admin.
        /// </summary>
        public static string RunasAdmin {
            get {
                return ResourceManager.GetString("RunasAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as Admin:.
        /// </summary>
        public static string RunasAdminLabel {
            get {
                return ResourceManager.GetString("RunasAdminLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ServerHeading {
            get {
                return ResourceManager.GetString("ServerHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP:.
        /// </summary>
        public static string ServerIPLabel {
            get {
                return ResourceManager.GetString("ServerIPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Port:.
        /// </summary>
        public static string ServerPortLabel {
            get {
                return ResourceManager.GetString("ServerPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Client.
        /// </summary>
        public static string StartClientButton {
            get {
                return ResourceManager.GetString("StartClientButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Server.
        /// </summary>
        public static string StartServerButton {
            get {
                return ResourceManager.GetString("StartServerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized LEDs.
        /// </summary>
        public static string SyncedLEDsLabel {
            get {
                return ResourceManager.GetString("SyncedLEDsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having an issue or need help setting up this program?.
        /// </summary>
        public static string TechSupportCTA {
            get {
                return ResourceManager.GetString("TechSupportCTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech Support.
        /// </summary>
        public static string TechSupportItem {
            get {
                return ResourceManager.GetString("TechSupportItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JackNet RGB Sync - Configuration.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations provided by:.
        /// </summary>
        public static string TranslationsLabel {
            get {
                return ResourceManager.GetString("TranslationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to JackNet RGB Sync is available. Would you like to update?.
        /// </summary>
        public static string UpdateAvaiableText {
            get {
                return ResourceManager.GetString("UpdateAvaiableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update:.
        /// </summary>
        public static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available!.
        /// </summary>
        public static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
    }
}
