//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RGBSyncPlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RGBSyncPlus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Crash_SubTitleText {
            get {
                return ResourceManager.GetString("Crash.SubTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB Sync Studio has crashed..
        /// </summary>
        public static string Crash_TitleText {
            get {
                return ResourceManager.GetString("Crash.TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string Dialog_CopyCommand {
            get {
                return ResourceManager.GetString("Dialog.CopyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Dialog_No {
            get {
                return ResourceManager.GetString("Dialog.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoPremiumTitle.
        /// </summary>
        public static string Dialog_NoPremiumTitle {
            get {
                return ResourceManager.GetString("Dialog.NoPremiumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently using the latest version of the app..
        /// </summary>
        public static string Dialog_NoUpdateText {
            get {
                return ResourceManager.GetString("Dialog.NoUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Update Available.
        /// </summary>
        public static string Dialog_NoUpdateTitle {
            get {
                return ResourceManager.GetString("Dialog.NoUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Dialog_OKCommand {
            get {
                return ResourceManager.GetString("Dialog.OKCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to RGB Sync is available. Would you like to update?.
        /// </summary>
        public static string Dialog_UpdateText {
            get {
                return ResourceManager.GetString("Dialog.UpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string Dialog_UpdateTitle {
            get {
                return ResourceManager.GetString("Dialog.UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Dialog_Yes {
            get {
                return ResourceManager.GetString("Dialog.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as Admin:.
        /// </summary>
        public static string Settings_AdminLabel {
            get {
                return ResourceManager.GetString("Settings.AdminLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminText.
        /// </summary>
        public static string Settings_AdminText {
            get {
                return ResourceManager.GetString("Settings.AdminText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Delay:.
        /// </summary>
        public static string Settings_DelayLabel {
            get {
                return ResourceManager.GetString("Settings.DelayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DelayToolTip.
        /// </summary>
        public static string Settings_DelayToolTip {
            get {
                return ResourceManager.GetString("Settings.DelayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Settings_DelayUnit {
            get {
                return ResourceManager.GetString("Settings.DelayUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices:.
        /// </summary>
        public static string Settings_DevicesLabel {
            get {
                return ResourceManager.GetString("Settings.DevicesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord:.
        /// </summary>
        public static string Settings_DiscordLabel {
            get {
                return ResourceManager.GetString("Settings.DiscordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiscordText.
        /// </summary>
        public static string Settings_DiscordText {
            get {
                return ResourceManager.GetString("Settings.DiscordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiscordToolTip.
        /// </summary>
        public static string Settings_DiscordToolTip {
            get {
                return ResourceManager.GetString("Settings.DiscordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Settings_LanguageLabel {
            get {
                return ResourceManager.GetString("Settings.LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Minimization:.
        /// </summary>
        public static string Settings_MinimizationLabel {
            get {
                return ResourceManager.GetString("Settings.MinimizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinimizationText.
        /// </summary>
        public static string Settings_MinimizationText {
            get {
                return ResourceManager.GetString("Settings.MinimizationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling Rate:.
        /// </summary>
        public static string Settings_PollingRateLabel {
            get {
                return ResourceManager.GetString("Settings.PollingRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollingRateTooltip.
        /// </summary>
        public static string Settings_PollingRateToolTip {
            get {
                return ResourceManager.GetString("Settings.PollingRateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollingRateUnit.
        /// </summary>
        public static string Settings_PollingRateUnit {
            get {
                return ResourceManager.GetString("Settings.PollingRateUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.ThemeApplyBtnText.
        /// </summary>
        public static string Settings_ThemeApplyBtnText {
            get {
                return ResourceManager.GetString("Settings.ThemeApplyBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string Settings_ThemeLabel {
            get {
                return ResourceManager.GetString("Settings.ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Update.
        /// </summary>
        public static string Settings_UpdateBtnText {
            get {
                return ResourceManager.GetString("Settings.UpdateBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates:.
        /// </summary>
        public static string Settings_UpdateLabel {
            get {
                return ResourceManager.GetString("Settings.UpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Settings_VersionLabel {
            get {
                return ResourceManager.GetString("Settings.VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental.
        /// </summary>
        public static string Store_ExperimentalBtnText {
            get {
                return ResourceManager.GetString("Store.ExperimentalBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Store_FilterLabel {
            get {
                return ResourceManager.GetString("Store.FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Store_Plugin_DisableBtnLabel {
            get {
                return ResourceManager.GetString("Store.Plugin.DisableBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed .
        /// </summary>
        public static string Store_Plugin_InstallBtnLabel {
            get {
                return ResourceManager.GetString("Store.Plugin.InstallBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed .
        /// </summary>
        public static string Store_Plugin_InstalledBtnLabel {
            get {
                return ResourceManager.GetString("Store.Plugin.InstalledBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Store_Plugin_UninstallBtnLabel {
            get {
                return ResourceManager.GetString("Store.Plugin.UninstallBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions.
        /// </summary>
        public static string Store_Plugin_VersionsBtnLabel {
            get {
                return ResourceManager.GetString("Store.Plugin.VersionsBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Store.
        /// </summary>
        public static string Store_RefreshBtnText {
            get {
                return ResourceManager.GetString("Store.RefreshBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart All.
        /// </summary>
        public static string Store_RestartAllBtnText {
            get {
                return ResourceManager.GetString("Store.RestartAllBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit App.
        /// </summary>
        public static string TrayMenu_ExitAppItem {
            get {
                return ResourceManager.GetString("TrayMenu.ExitAppItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open App.
        /// </summary>
        public static string TrayMenu_OpenUIItem {
            get {
                return ResourceManager.GetString("TrayMenu.OpenUIItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart App.
        /// </summary>
        public static string TrayMenu_RestartAppItem {
            get {
                return ResourceManager.GetString("TrayMenu.RestartAppItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech Support.
        /// </summary>
        public static string TrayMenu_TechSupportItem {
            get {
                return ResourceManager.GetString("TrayMenu.TechSupportItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string UI_AboutTabHeader {
            get {
                return ResourceManager.GetString("UI.AboutTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB Sync.
        /// </summary>
        public static string UI_AppName {
            get {
                return ResourceManager.GetString("UI.AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string UI_DeviceTabHeader {
            get {
                return ResourceManager.GetString("UI.DeviceTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string UI_ProfileTabHeader {
            get {
                return ResourceManager.GetString("UI.ProfileTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string UI_SettingsTabHeader {
            get {
                return ResourceManager.GetString("UI.SettingsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string UI_StoreTabHeader {
            get {
                return ResourceManager.GetString("UI.StoreTabHeader", resourceCulture);
            }
        }
    }
}
